### PR TITLE
A small change in the list title and review pt_BR translation

### PR DESCRIPTION
**Pull request by leandrocunha526**
When "no task list" appears listing the lists below the title, the negation doesn't make much sense and yet I removed that negation.

Along with this change, the Brazilian Portuguese translation file was revised, the necessary changes were made, such as adding credit to Guilherme Berbet and the update was made following some lines of the file.

### CODE REVIEW

**Comment by leandrocunha526** [comment]
Now:
With negation and tasks lists presents.
Captura de tela de 2024-10-08 19-16-19
PT: Sem listas de tarefas
EN: No Tasks Lists

With this merge request:
No negation and tasks lists presents.
image

**Comment by rffontenelle** [comment]
Changing manually the POT file doesn't make sense, as POT files are generated based on the translstable strings in the source files.

Please make sure to change the software and regenerate the POT instead.

**Comment by leandrocunha526** [comment]
> Changing manually the POT file doesn't make sense, as POT files are generated based on the translstable strings in the source files.
> 
> Please make sure to change the source and regenerate the POT instead.

It was edited to remove just one "no". If we regenerated the file this no could appear again and that is what may have happened in this case. This "no" was not supposed to exist.

**Comment by mrvladus** [comment]
"No task lists" is only appears in status page when no task lists is in sidebar

**Comment by leandrocunha526** [comment]
> "No task lists" is only appears in status page when no task lists is in sidebar

It was appearing after creating tasks @mrvladus.

**Pull request merged**
