### PR TITLE
Update Persian Translation

### PR DESCRIPTION
**Pull request by hadi-f90**
It seems fa.po file is not as updated as the app itself. courtesy of Danial Behzadi, I tried to complete his work.

### CODE REVIEW

**Comment by hadi-f90** [comment]
By the way, I couldn't find language switcher anywhere in the app.

**Comment by mrvladus** [comment]
There is no language switcher, it follows system locale settings.

**Comment by hadi-f90** [comment]
How about giving users an option for doing this?

**Comment by mrvladus** [comment]
I don't really see the point. Why not just switch system language? No other gnome app is doing that. The only apps that I've seen doing language switch is browsers. I can understand it for browsers (privacy reasons), but for any other app it's  unnecessary.

**Pull request merged**
