### PR TITLE
A small info bar now appears in the listview for each task

### PR DESCRIPTION
**Pull request by belsabbagh**

### CODE REVIEW

**Comment by belsabbagh** [comment]
This is how it looks like now

image

**Comment by belsabbagh** [comment]
I fixed the styling so the text doesn't look overwhelming at first glance

image

**Comment by mrvladus** [comment]
Hi! Check out `dev` branch, I already do something similar.

**Comment by belsabbagh** [comment]
Hello! I didn't notice that, but I just checked it and I like how you did it. Can I work on that?

**Comment by mrvladus** [comment]
Yes, what you would like to do?

**Comment by belsabbagh** [comment]
I'm thinking I want the date selector to be able to choose a range. I also want to make the notes section more obvious that it's an editable text area by having a label or placeholder in the pop up.

I also want to add a readable so that I wouldn't have to click to see the task details.

The priority selector is selecting more than one but it may be a problem just on my end.
image

The date selector isn't showing for me but I'll check its source and see what its like.
image

**Comment by mrvladus** [comment]
I didn't added date widget yet, I wanted to port in to using GtkTemplate and .ui files. Priority is not finished yet too, it's just a sketch on how I wanted it to look. 
> I also want to add a readable so that I wouldn't have to click to see the task details.
I didn't get that, can yo explain?
>  make the notes section more obvious
Yeah, it's a good idea.

**Comment by belsabbagh** [comment]
I meant that I wanted to have an info bar like my implementation so that on first glance i can see the info about the task without having to expand the task to read the info

**Comment by mrvladus** [comment]
We can toggle toolbar on for tasks that have some of the properties set, e.g date, notes, priority. And leave it toggled off when task doesn't have properties set.

**Comment by belsabbagh** [comment]
That sounds good. I like that.

I won't continue with this branch and instead I'll base a new one on the `dev` branch to be up to date with the latest changes.

**Comment by mrvladus** [comment]
Added in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)

**Pull request closed without merging**
