### PR TITLE
Reusable windows instead of popovers

### PR DESCRIPTION
**Pull request by sim6**
This changes improve noticeably the performance when list a lot of tasks.

### CODE REVIEW

**Comment by mrvladus** [comment]
Looks good, but I don't think we need details window. Popup is enough. And you can remove `RAISED` style for ToolbarView. And for the priority window we need to add `navigation-sidebar` class for ListBox. I wanted to redisign it later, but it will be good for now.

**Comment by sim6** [comment]
Thanks. I removed `RAISED` style and added `navigation-sidebar` class. About window Details, with the current code there are a menu with color widgets for each task, so a lot of widgets in a list with a lot of tasks, but with window Details there is only a widget of each and is reused for all tasks.

**Comment by mrvladus** [comment]
Is the any way we can reuse popups?

**Comment by sim6** [comment]
Sure, but I prefer `Adw.Dialog` because I like the application more homogeneous and also it is more usable on small touch screens like the one Librem5 comes with.

**Comment by mrvladus** [comment]
Closing this because of #339. I've implemented almost all dialogs. Python was getting in the way of improving performance.

**Pull request closed without merging**
