### PR TITLE
Catalan translation

### PR DESCRIPTION
**Pull request by 4rune**
Translated everything that was missing to translate, sorry because I do not know how to apply the changes and prove that the translation has been applied correctly, I tried to save the .po file in the directory of the original folder but I can not find the path to the application, if you tell me what it is I try it right now, sorry I'm a github noob :'

### CODE REVIEW

**Comment by mrvladus** [comment]
It should wok just fine! Thank you!

**Comment by mrvladus** [comment]
I have a script for running flatpak at `build-aux/run.sh`

**Comment by 4rune** [comment]
> It should wok just fine! Thank you!

np <3

**Comment by 4rune** [comment]
hey, first of all, thanks for applying the new Catalan translation! It is very important for me and the rest of us who love the language, I wanted to comment that, by my mistake I belive, I don't appear in the translation credits and well I would be rlly happy if my name appeared ^^' (and in the .po file if it appears in the "translator-credits" section), as I'm new in this I don't know if it is that it is badly written or the syntax is not the correct one, sorry :( 

imatge

**Comment by mrvladus** [comment]
Hi! I'll try to fix that, I just need to read the docs, because until now there was only one translator per language 😃

**Comment by 4rune** [comment]
> Hi! I'll try to fix that, I just need to read the docs, because until now there was only one translator per language 😃

ty so much <3

**Comment by mrvladus** [comment]
I figured it out! It need to be like this for multiple translators:
```
msgid "translator-credits"
msgstr ""
"cubells <vicent@vcubells.net>\n"
"arnau ferreres <arnauarquer@gmail.com>"
```
It's a little bit strange but it works 😄 
Снимок экрана от 2023-11-28 18-07-03
It will be in the next update.

**Pull request merged**
